local md = peripheral.wrap("left")
local m = peripheral.wrap("top")
while true do
    m.clear()
    m.setTextScale(1.5)
    m.setTextColor(colors.red)
    m.setCursorPos(1,1)
    m.write("Come To The")
    m.setCursorPos(1,2)
    m.setTextColor(colors.purple)
    m.write("Star Arcade")
    m.setCursorPos(1,3)
    m.setTextColor(colors.gray)
    m.write("==========================================================")
    md.clear()
    md.setTextScale(1)
    md.setCursorPos(1,1)
    md.setTextColor(colors.blue)
    md.write("Play Some Games With Us")
    md.setCursorPos(1,2)
    md.write("Play Games Like")
    md.setCursorPos(1,3)
    md.write("Chess")
    md.setCursorPos(1,4)
    md.write("Zombie Tag")
    md.setCursorPos(29-26,12)
    md.setTextColor(colors.lightGray)
    md.write("Dial: 1-22-16-34-32-6-28-7")
    sleep(.1)
end